function generatePoem(event) {
  event.preventDefault();

  new Typewriter("#poem", {
    strings: "Here you have a french poem generated by AI",
    autoStart: true,
    delay: 1,
    cursor: "",
  });
}

let poemFormElement = document.querySelector("#poem-generator-form");
poemFormElement.addEventListener("submit", generatePoem);
